Scholl_management_WebApplication/Controllers/CountryController.cs
using Scholl_management_WebApplicationmodel.Model;
using Scholl_management_WebApplicationRepository.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace Scholl_management_WebApplication.Controllers
{
    public class CountryController : Controller
    {
        public CoutryInterface _CoutryInterface;
        public CountryController(CoutryInterface coutryInterface)
        {
            _CoutryInterface = coutryInterface;
        }

        // GET: Country
        public ActionResult AddCountry()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCountry(Countrymodel countrymodels)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (_CoutryInterface.addCountry(countrymodels) == true)
                    {
                        return RedirectToAction("CountryList");
                    }
                }
                return View();
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }
        public ActionResult CountryList(int ? id)
        {
            try
            {
                return View(_CoutryInterface.dbcountries().ToPagedList(id ?? 1,3));
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }
        public ActionResult Delete(int id)
        {
            try
            {
                _CoutryInterface.DeleteCountry(id);

                return RedirectToAction("CountryList");
            }
            catch(Exception ex)
            {
                throw ex;
            }
         
        }
        public ActionResult Edit(int id)
        {
            try
            {
                return View(_CoutryInterface.EditCountry(id));
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }
        [HttpPost]
        public ActionResult Edit(int id, Countrymodel countrymodels)
        {
            try { 
            if (_CoutryInterface.UpdateCountry(id, countrymodels))
            {

                return RedirectToAction("CountryList");
            }
            return View();
        }
            catch (Exception ex)
            {
                throw ex;
            }
        }

    }
}

Scholl_management_WebApplication/Views/Country/AddCountry.cshtml
@model Scholl_management_WebApplicationmodel.Model.Countrymodel
@{
    Layout =
"~/Views/Shared/_dashboard.cshtml";
}
@{
     ViewBag.Title = "AddCountry";
}

<h2>AddCountry</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*<h4>Countrymodel</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CountryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CountryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CountryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "CountryList")
</div>

Scholl_management_WebApplication/Views/Country/CountryList.cshtml
@model IPagedList<Scholl_management_WebApplicationmodel.Dbconnection.Country>

@{
    Layout =
"~/Views/Shared/_dashboard.cshtml";
}
@{
    ViewBag.Title = "CountryList";
}
@using PagedList;
@using PagedList.Mvc;

<h2>CountryList</h2>

<p>
    @Html.ActionLink("Create New", "AddCountry")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().CountryName)
        </th>
        <th>Action</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CountryName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>
@Html.PagedListPager( Model, id => Url.Action("CountryList", "Country", new { id }))

Scholl_management_WebApplication/Views/Country/Edit.cshtml
@model Scholl_management_WebApplicationmodel.Model.Countrymodel
@{
    Layout = "~/Views/Shared/_dashboard.cshtml";
}
@{
ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Countrymodel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CountryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CountryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CountryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "CountryList")
</div>